config/routes.rb
Rails.application.routes.draw do

  root "topics#index"

  # Topics routes
  resources :topics do
    resources :posts
  end

  resources :posts do
    resources :likes
  end

  # User routes
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy] do
    resources :inboxes, :messages
  end

  # Sessions routes
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inbox.rb
class Inbox < ApplicationRecord
  belongs_to :user
  has_many :messages
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :inbox
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic, :touch => true
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_rich_text :content
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :title, presence: true, length: { minimum: 8 }
  belongs_to :user
  has_many :posts, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_secure_password

  has_many :topics
  has_many :posts
  has_many :messages
  has_one :inbox, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inboxes_controller.rb
class InboxesController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post, :find_user

  def create
    if already_liked?
      flash[:notice] = "You can't like a post more than once."
    else
      @post.likes.create(user_id: @user.id)
    end
    redirect_to topic_path(@post.topic)
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_user
    @user = User.find_by_id(session[:user_id])
  end

  def already_liked?
    Like.where(user_id: @user.id, post_id:
    params[:post_id]).exists?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_user

  def show
    find_message_owner();
    @user = User.find(params[:user_id])
    if (@current_user == @user) && (@current_user == @message_owner)
    @message = Message.find(params[:id])
    else
      redirect_to user_path(@current_user)
    end
  end

  def create
    if @current_user
      @user = User.find(params[:user_id])
      @message = @user.inbox.messages.create(message_params.merge(user_id: @current_user.id))
      redirect_to user_path(@current_user)
    else
      @user = User.find(params[:user_id])
      redirect_to user_path(@user)
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to user_path(@current_user)
  end

  private

  def message_params
    params.require(:message).permit(:title, :body)
  end

  def find_message_owner
    @message_owner = Message.find(params[:id]).inbox.user
  end

  def find_user
    @current_user = User.find_by_id(session[:user_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_user

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.create(post_params.merge(user_id: @user.id))
    redirect_to topic_path(@topic)
  end

  def edit
    if @user.id == Post.find(params[:id]).user.id
      @post = Post.find(params[:id])
    else
      redirect_to topic_path(Post.find(params[:id]).topic)
    end
  end

  def update
    @post = Post.find(params[:id])
    if @user.id == @post.user.id
      if @post.update(post_params)
        redirect_to topic_path(Post.find(params[:id]).topic)
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to topic_path(Post.find(params[:id]).topic)
    end
  end 

  private
    def post_params
      params.require(:post).permit(:content)
    end

    def find_user
      @user = User.find_by_id(session[:user_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login

  end

  def create
    @user = User.find_by(username: params[:username])

    if !!@user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      @user.touch(:last_login)
      redirect_to root_path
    else
      message = "Login failed! Please make sure username and password are correct."
      redirect_to login_path, notice: message
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :find_user

  def index
    @topics = Topic.all.order(updated_at: :desc)
    @topics = Kaminari.paginate_array(@topics).page(params[:page]).per(10)
  end

  def show
    @topic = Topic.find(params[:id])
    @posts = @topic.posts.order(created_at: :desc).reverse
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(10)
    @topic.increment!(:view)
  end

  def new
    if @user
      @topic = Topic.new
    else
      redirect_to root_path
    end
  end

  def create
    if @user
      @topic = Topic.create(topic_params.merge(user_id: @user.id))
      if @topic.save
        @topic.posts.create(post_params.merge(user_id: @user.id))
        redirect_to @topic
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def edit
    if @user.id == Topic.find(params[:id]).user.id
      @topic = Topic.find(params[:id])
    else
      redirect_to topic_path(Topic.find(params[:id]))
    end
  end

  def update
    @topic = Topic.find(params[:id])
    if @user.id == @topic.user.id
      if @topic.update(topic_params)
        redirect_to @topic
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to topic_path(@topic)
    end
  end 

  private
    def topic_params
      params.require(:topic).permit(:title)
    end

    def post_params
      params.require(:topic).permit(:content)
    end

    def find_user
      @user = User.find_by_id(session[:user_id])
    end
end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      @user.touch(:last_login)
      Inbox.create(user_id: @user.id)
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @users = User.order(:id).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    if @current_user == User.find(params[:id])
      @user = User.find(params[:id])
    end
  end

  def update
    if @current_user == User.find(params[:id])
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to @user
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :avatar, :bio)
  end

  def find_user
    @current_user = User.find_by_id(session[:user_id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
  end

  def profile_user
    @profile_user = User.find(params[:user_id])
  end
end

app/helpers/inboxes_helper.rb
module InboxesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/messages/_form.html.erb
<div class="form-group-wrap">
  <%= form_with model: [ profile_user, profile_user.inbox.messages.build ] do |form| %>
    <div class="form-group mt-4">
      <%= form.label :title, class:"control-label"%><br>
      <%= form.text_field :title, class:"form-control" %>
      <% current_user.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="form-group mt-4">
      <%= form.label :body, class:"control-label"%><br>
      <%= form.text_area :body, class:"form-control" %>
      <% current_user.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="form-group">
      <%= form.submit "Send", :class => "btn btn-primary mt-4" %>
    </div>
  <% end %>
</div>

app/views/messages/_message.html.erb
<tr>
  <td><%= link_to message.user.username, user_path(message.user) %></td>
  <td><%= link_to message.title, user_message_path(message.inbox.user, message) %></td>
  <td><%= time_ago_in_words(message.created_at) %> ago</td>
  <td><%= link_to "Delete", user_message_path(message.inbox.user, message), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } , class: "btn btn-primary btn-sm"%></td>
</tr>

app/views/messages/new.html.erb
<h1>Send a message</h1>
<%= render "form" %>

app/views/messages/show.html.erb
<div class="mb-3">
  <div class="row">
    <div class="col-md-4 col-lg-2">
      <div class="p-3">
        <% if @message.user.avatar.attached? %>
          <%= image_tag @message.user.avatar, :class => "img-fluid mb-2" %>
        <% end %>
        <h2>
          <%= link_to @message.user.username, user_path(@message.user) %>
        </h2>
        <p>Posts: <%= @message.user.posts.count %><br/>
        Joined: <%= @message.user.created_at.strftime("%d %B %G") %></p>
      </div>
    </div>
    <div class="col-md-8 col-lg-10">
      <div class="card full-height">
        <div class="content-spaced card-body">
          <div>
            <h2>
              <%= @message.title %>
            </h2>
            <p>
              <%= @message.body %>
            </p>
          </div>
        </div>
      </div>
      <%= link_to "Reply", new_user_message_path(@message.user), class: "btn btn-primary btn-outline mt-2 mb-5" %>
    </div>
  </div>
</div>

app/views/posts/_created.html.erb
<% if post.created_at.strftime("%d %B %G - %H:%M") == post.updated_at.strftime("%d %B %G - %H:%M") %>
  <small class="text-muted">Posted: <%= time_ago_in_words(post.created_at) %> ago</small>
<% else %>
  <small class="text-muted">Last edited: <%= time_ago_in_words(post.updated_at) %> ago</small>
<% end %>

app/views/posts/_form.html.erb
<div class="form-group-wrap">
  <%= form_with model: [ @topic, @topic.posts.build ] do |form| %>
    <div class="form-group mt-4">
      <%= form.rich_text_area :content, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= form.submit "Reply", :class => "btn btn-primary mt-4" %>
    </div>
  <% end %>
</div>

app/views/posts/_likes.html.erb
<% case post.likes.count
  when 0 %>
  <% when 1 %>
    <p class="likes">
        <%= link_to post.likes.first.user.username, user_path(post.likes.first.user) %> liked this
    </p> 
  <% when 2 %>
    <p class="likes">
        <% post.likes.first(2).each do |like| %>      
          <span><%= link_to like.user.username, user_path(like.user) %></span>
        <% end %> likes this
    </p>
  <% else %>
    <p class="likes">
        <% post.likes.first(2).each do |like| %>      
          <span><%= link_to like.user.username, user_path(like.user) %></span>
        <% end %> and <%= post.likes.count - 2 %> more likes this
    </p>
<% end %>

app/views/posts/_post-thread.html.erb
<p class="mt-4">Posted in: <%= link_to post.topic.title, topic_path(post.topic.id) %>
<%= render post %>

app/views/posts/_post.html.erb
<div class="mb-3">
  <div class="row">
    <div class="col-md-4 col-lg-2">
      <div class="p-3">
        <% if post.user.avatar.attached? %>
          <%= image_tag post.user.avatar, :class => "img-fluid mb-2" %>
        <% end %>
        <h2>
          <%= link_to post.user.username, user_path(post.user) %>
        </h2>
        <p>Posts: <%= post.user.posts.count %><br/>
        Joined: <%= post.user.created_at.strftime("%d %B %G") %></p>
      </div>
    </div>
    <div class="col-md-8 col-lg-10">
      <div class="card full-height">
        <div class="content-spaced card-body">
          <div>
              <%= render partial: "posts/likes", locals: {post: post} %>
            <p>
              <%= post.content %>
            </p>
          </div>
          <div class="text-end">
            <%= render partial: "posts/created", locals: {post: post} %>
            <% if current_user == post.user %>
              <%= link_to 'Edit', edit_topic_post_path(post.topic, post), class: "inline btn btn-sm btn-primary ml-3" %>
            <% end %>
            <% if logged_in? %>
            <%= button_to 'Like', post_likes_path(post), method: :post, class: "inline btn btn-sm btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<div class="form-group-wrap">
  <%= form_with model: @post do |form| %>
    <div class="form-group mt-4">
      <%= form.rich_text_area :content, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= form.submit "Edit", :class => "btn btn-primary mt-4" %>
    </div>
  <% end %>
</div>

<br>

<div>
  <%= link_to "Show this topic", @post.topic %> |
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/_form.html.erb
<%= form_with model: topic do |form| %>
  <div class="form form-horizontal">
    <div class="form-group mt-4">
      <%= form.label :title, class:"control-label"%><br>
      <%= form.text_field :title, class:"form-control" %>
      <% topic.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="form-group mt-4">
      <%= form.label :content, class:"control-label" %><br>
      <%= form.rich_text_area :content, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= form.submit "Create", :class => "btn btn-primary mt-4" %>
    </div>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div class="card mb-1">
  <div class="card-body">
    <div class="row align-items-center">
      <div class="col-sm-6 col-lg-8">
        <h2><%= link_to topic.title, topic%></h2>
        <p><small>Created <%= topic.created_at.strftime("%d %B %G") %> by <%= link_to topic.user.username, user_path(topic.user)%></small></p>
      </div>
      <div class="col-sm-2 col-lg-1 text-end">
        <%= topic.view %>
        <i class="bi bi-eye-fill"></i>
      </div>
      <div class="col-sm-2 col-lg-1 text-end">
        <%= topic.posts.count %>
        <i class="bi bi-chat-left-fill"></i>
      </div>
      <div class="col-sm-2 col-lg-2">
        <p class="text-end"><small>
        <%= time_ago_in_words(topic.posts.last.updated_at) %> ago<br/>
        <%= link_to topic.posts.last.user.username, user_path(topic.posts.last.user)%></small></p>
      </div>
    </div>

  </div>
</div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Show this topic", @topic %> |
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/index.html.erb
<% content_for :navlinks do %>
  <% if logged_in? %>
    <li class="nav-item">
      <%= link_to "New Thread", new_topic_path, class: "btn btn-primary" %>
    </li>
  <% end %>
<% end %>


  <h1>Threads</h1>
  <div class="card thread-header px-3 py-2 bg-primary text-white mb-2 mt-4">
    <div class="row align-items-center">
      <div class="col-sm-6 col-lg-8">
        <p><strong>Title</strong></p>
      </div>
      <div class="col-sm-2 col-lg-1 text-end">
        <p><strong>Views</strong></p>
      </div>
      <div class="col-sm-2 col-lg-1 text-end">
        <p><strong>Posts</strong></p>
      </div>
      <div class="col-sm-2 col-lg-2 text-end">
        <p><strong>Latest post</strong></p>
      </div>
    </div>
  </div>
  <div class="mt-3">
    <%= paginate @topics %>
    <%= render @topics %>
    <%= paginate @topics %>
  </div>

app/views/topics/new.html.erb
<h1>Create a new thread topic</h1>
<%= render "form", topic: @topic %>

<div class="mt-4">
  <%= link_to "Back to threads", topics_path %>
</div>

app/views/topics/show.html.erb
<% content_for :head do %>
  - <%= @topic.title %>
<% end %>

<div class="card card-body bg-primary text-white mb-4">
  <h1><%= @topic.title %></h1>
  <p>Created <%= @topic.created_at.strftime("%d %B %G") %> by <%= link_to @topic.user.username, user_path(@topic.user)%></p>
</div>

<%= paginate @posts %>
<%= render @posts %>

<% if logged_in? %>
  <%= render 'posts/form' %>
<% else %>
<p>Please login to join the conversation</p>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
    <div class="form-group mt-4">
      <%= form.label :username, class:"control-label"%><br>
      <%= form.text_field :username, class:"form-control"%>
      <% user.errors.full_messages_for(:username).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="form-group mt-4">
      <%= form.label :bio, class:"control-label" %><br>
      <%= form.text_area :bio, class: "form-control"  %>
      <% user.errors.full_messages_for(:bio).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="form-group mt-4">
      <%= form.label :avatar, class:"control-label" %><br>
      <%= form.file_field :avatar, class: "form-control"  %>
      <% user.errors.full_messages_for(:avatar).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="form-group mt-4">
      <%= form.label :password, class:"control-label" %><br>
      <%= form.password_field :password, class: "form-control"  %>
      <% user.errors.full_messages_for(:password).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div class="form-group">
      <%= form.submit "Submit", :class => "btn btn-primary mt-4" %>
    </div>
  <% end %>

app/views/users/edit.html.erb
<h1>Edit account details</h1>
<%= render "form", user: @user %>

app/views/users/new.html.erb
<h1>Create a new account</h1>
<%= render "form", user: @user %>

app/views/users/show.html.erb
<% content_for :head do %>
  - <%= @user.username %>'s profile
<% end %>
<div class="bg-light p-3">
  <div class="profile row">
    <div class="col-sm-2">
      <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar, :class => "img-fluid rounded" %>
      <% end %>
    </div>
    <div class="col-sm-10">
      <h1><%= @user.username %></h1>
      <p>Member since: <%= @user.created_at.strftime("%d %B %G") %> <br/>
      Posts: <%= @user.posts.count %> <br/>
      
      Last login: <%= time_ago_in_words(@user.last_login) %> ago</p>
      <% if current_user == @user %>
        <%= link_to "Edit", edit_user_path(@user), class: "btn btn-primary btn-outline mt-2 mb-5" %>
      <% end %>
      <% if current_user != @user && logged_in? %>
        <%= link_to "Message", new_user_message_path(@user), class: "btn btn-primary btn-outline mt-2 mb-5" %>
      <% end %>
    </div>
  </div>
</div>

<hr class="my-5" />

<ul class="nav nav-pills my-4" id="pills-tab" role="tablist">

  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="pills-posts-tab" data-bs-toggle="pill" data-bs-target="#pills-posts" type="button" role="tab" aria-controls="pills-posts" aria-selected="false">Post History</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">About</button>
  </li>
  <% if current_user == @user %>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pills-inbox-tab" data-bs-toggle="pill" data-bs-target="#pills-inbox" type="button" role="tab" aria-controls="pills-inbox" aria-selected="true">Inbox</button>
    </li>
  <% end %>
</ul>
<div class="tab-content mt-3" id="pills-tabContent">
  <div class="tab-pane fade  show active" id="pills-posts" role="tabpanel" aria-labelledby="pills-posts-tab">
    <% unless @user.posts.count == 0 %>
      <%= render partial: "posts/post-thread", collection: @user.posts.last(5), as: :post %>
    <% else %>
      <p>Looks like this user hasn't posted anything.</p>
    <% end %>
  </div>
  <div class="tab-pane fade" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
    <div class="card mt-2">
      <div class="card-body">
        <% if @user.bio %>
          <p><%= @user.bio %></p>
        <% else %>
          <p>This user does not yet have a bio.</p>
        <% end %>
      </div>
    </div>
  </div>
  <% if current_user == @user %>
    <div class="tab-pane fade" id="pills-inbox" role="tabpanel" aria-labelledby="pills-inbox-tab">
      <div class="card mt-2">
        <div class="card-body">
            <% unless @user.inbox.messages.count == 0 %>
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Date</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                  <%= render @user.inbox.messages.order(created_at: :desc) %>
                </tbody>
              </table>
              
            <% else %>
              <p>No messages.</p>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>