config/routes.rb
Rails.application.routes.draw do

  root "topics#index"

  # Topics routes
  resources :topics do
    resources :posts
  end

  resources :posts do
    resources :likes
  end

  # User routes
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy] do
    resources :inboxes, :messages
  end

  # Sessions routes
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inbox.rb
class Inbox < ApplicationRecord
  belongs_to :user
  has_many :messages
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :inbox
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic, :touch => true
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_rich_text :content
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :title, presence: true, length: { minimum: 8 }
  belongs_to :user
  has_many :posts, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_secure_password

  has_many :topics
  has_many :posts
  has_many :messages
  has_one :inbox, dependent: :destroy
end

app/controllers/inboxes_controller.rb
class InboxesController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post, :find_user

  def create
    if already_liked?
      flash[:notice] = "You can't like a post more than once."
    else
      @post.likes.create(user_id: @user.id)
    end
    redirect_to topic_path(@post.topic)
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_user
    @user = User.find_by_id(session[:user_id])
  end

  def already_liked?
    Like.where(user_id: @user.id, post_id:
    params[:post_id]).exists?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_user

  def show
    find_message_owner();
    @user = User.find(params[:user_id])
    if (@current_user == @user) && (@current_user == @message_owner)
    @message = Message.find(params[:id])
    else
      redirect_to user_path(@current_user)
    end
  end

  def create
    if @current_user
      @user = User.find(params[:user_id])
      @message = @user.inbox.messages.create(message_params.merge(user_id: @current_user.id))
      redirect_to user_path(@current_user)
    else
      @user = User.find(params[:user_id])
      redirect_to user_path(@user)
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to user_path(@current_user)
  end

  private

  def message_params
    params.require(:message).permit(:title, :body)
  end

  def find_message_owner
    @message_owner = Message.find(params[:id]).inbox.user
  end

  def find_user
    @current_user = User.find_by_id(session[:user_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_user

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.create(post_params.merge(user_id: @user.id))
    redirect_to topic_path(@topic)
  end

  def edit
    if @user.id == Post.find(params[:id]).user.id
      @post = Post.find(params[:id])
    else
      redirect_to topic_path(Post.find(params[:id]).topic)
    end
  end

  def update
    @post = Post.find(params[:id])
    if @user.id == @post.user.id
      if @post.update(post_params)
        redirect_to topic_path(Post.find(params[:id]).topic)
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to topic_path(Post.find(params[:id]).topic)
    end
  end 

  private
    def post_params
      params.require(:post).permit(:content)
    end

    def find_user
      @user = User.find_by_id(session[:user_id])
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :find_user

  def index
    @topics = Topic.all.order(updated_at: :desc)
    @topics = Kaminari.paginate_array(@topics).page(params[:page]).per(10)
  end

  def show
    @topic = Topic.find(params[:id])
    @posts = @topic.posts.order(created_at: :desc).reverse
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(10)
    @topic.increment!(:view)
  end

  def new
    if @user
      @topic = Topic.new
    else
      redirect_to root_path
    end
  end

  def create
    if @user
      @topic = Topic.create(topic_params.merge(user_id: @user.id))
      if @topic.save
        @topic.posts.create(post_params.merge(user_id: @user.id))
        redirect_to @topic
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def edit
    if @user.id == Topic.find(params[:id]).user.id
      @topic = Topic.find(params[:id])
    else
      redirect_to topic_path(Topic.find(params[:id]))
    end
  end

  def update
    @topic = Topic.find(params[:id])
    if @user.id == @topic.user.id
      if @topic.update(topic_params)
        redirect_to @topic
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to topic_path(@topic)
    end
  end 

  private
    def topic_params
      params.require(:topic).permit(:title)
    end

    def post_params
      params.require(:topic).permit(:content)
    end

    def find_user
      @user = User.find_by_id(session[:user_id])
    end
end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      @user.touch(:last_login)
      Inbox.create(user_id: @user.id)
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @users = User.order(:id).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    if @current_user == User.find(params[:id])
      @user = User.find(params[:id])
    end
  end

  def update
    if @current_user == User.find(params[:id])
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to @user
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :avatar, :bio)
  end

  def find_user
    @current_user = User.find_by_id(session[:user_id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
  end

  def profile_user
    @profile_user = User.find(params[:user_id])
  end
end

app/helpers/inboxes_helper.rb
module InboxesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodingForum <%= yield :head %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-light">
      <div class="container-fluid">
        <%= link_to image_tag("logo.png", width: 100, :class=>"img-fluid", alt: "Code Connect logo"), root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <% if logged_in? %>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav navbar-flex">
              <li class="nav-item inline-items">
                <span class="nav-link">Signed in as: <%= link_to current_user.username, user_path(current_user) %></span>
                <a class="nav-link" aria-current="page" href="<%=logout_path%>">Logout</a>
              </li>
              <%= yield :navlinks %>
            </ul>
          </div>
        <% else %>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="<%=login_path%>">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%=new_user_path%>">Sign Up</a>
              </li>

            </ul> 
          </div>
        <% end %>
      </div>
    </nav>
    <main class="pt-5">
      <div class="container pt-5 pb-4">
        <%= yield %>
      </div>
    </main>
  </body>
</html>